# Generated by Django 4.2.4 on 2023-09-19 08:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=ckeditor.fields.RichTextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='clientpartner',
            name='description',
            field=ckeditor.fields.RichTextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(default='Default description'),
        ),
    ]
